export const ImagesData = [
  {
    id: "CMkJ-oT4lsQ",
    slug: "a-group-of-people-standing-on-top-of-a-mountain-CMkJ-oT4lsQ",
    alternative_slugs: {
      en: "a-group-of-people-standing-on-top-of-a-mountain-CMkJ-oT4lsQ",
      es: "un-grupo-de-personas-de-pie-en-la-cima-de-una-montana-CMkJ-oT4lsQ",
      ja: "山の頂上に立つ人々のグループ-CMkJ-oT4lsQ",
      fr: "un-groupe-de-personnes-debout-au-sommet-dune-montagne-CMkJ-oT4lsQ",
      it: "un-gruppo-di-persone-in-piedi-sulla-cima-di-una-montagna-CMkJ-oT4lsQ",
      ko: "산-꼭대기에-서-있는-한-무리의-사람들-CMkJ-oT4lsQ",
      de: "eine-gruppe-von-menschen-die-auf-einem-berggipfel-stehen-CMkJ-oT4lsQ",
      pt: "um-grupo-de-pessoas-no-topo-de-uma-montanha-CMkJ-oT4lsQ",
    },
    created_at: "2024-05-22T09:25:53Z",
    updated_at: "2024-05-23T18:45:02Z",
    promoted_at: "2024-05-23T10:59:50Z",
    width: 2828,
    height: 4242,
    color: "#262626",
    blur_hash: "LNF5:J-:M{NG_4?bfljY_N%gR+ae",
    description: null,
    alt_description: "a group of people standing on top of a mountain",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1716369415085-4a6876f91840?ixid=M3w2MTU0MDR8MHwxfGFsbHwxfHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1716369415085-4a6876f91840?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHwxfHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1716369415085-4a6876f91840?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHwxfHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1716369415085-4a6876f91840?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHwxfHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1716369415085-4a6876f91840?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHwxfHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1716369415085-4a6876f91840",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-group-of-people-standing-on-top-of-a-mountain-CMkJ-oT4lsQ",
      html: "https://unsplash.com/photos/a-group-of-people-standing-on-top-of-a-mountain-CMkJ-oT4lsQ",
      download:
        "https://unsplash.com/photos/CMkJ-oT4lsQ/download?ixid=M3w2MTU0MDR8MHwxfGFsbHwxfHx8fHx8Mnx8MTcxNjQ5MDAyN3w",
      download_location:
        "https://api.unsplash.com/photos/CMkJ-oT4lsQ/download?ixid=M3w2MTU0MDR8MHwxfGFsbHwxfHx8fHx8Mnx8MTcxNjQ5MDAyN3w",
    },
    likes: 91,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "jrCUu0aF6YQ",
      updated_at: "2024-05-23T17:29:27Z",
      username: "malcoo",
      name: "Tomáš Malík",
      first_name: "Tomáš",
      last_name: "Malík",
      twitter_username: null,
      portfolio_url: "http://www.maliktomas.com",
      bio: "If you like my work, please support me on my PayPal :)",
      location: "Slovakia, Bratislava",
      links: {
        self: "https://api.unsplash.com/users/malcoo",
        html: "https://unsplash.com/@malcoo",
        photos: "https://api.unsplash.com/users/malcoo/photos",
        likes: "https://api.unsplash.com/users/malcoo/likes",
        portfolio: "https://api.unsplash.com/users/malcoo/portfolio",
        following: "https://api.unsplash.com/users/malcoo/following",
        followers: "https://api.unsplash.com/users/malcoo/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-fb-1539459502-03cef6b596c8.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-fb-1539459502-03cef6b596c8.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-fb-1539459502-03cef6b596c8.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "tomas_malco_malik",
      total_collections: 0,
      total_likes: 1,
      total_photos: 489,
      total_promoted_photos: 146,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "tomas_malco_malik",
        portfolio_url: "http://www.maliktomas.com",
        twitter_username: null,
        paypal_email: null,
      },
    },
  },
  {
    id: "UHHFYUTz_n0",
    slug: "a-black-building-with-a-clock-on-the-side-of-it-UHHFYUTz_n0",
    alternative_slugs: {
      en: "a-black-building-with-a-clock-on-the-side-of-it-UHHFYUTz_n0",
      es: "un-edificio-negro-con-un-reloj-a-un-lado-UHHFYUTz_n0",
      ja: "側面に時計が置かれた黒い建物-UHHFYUTz_n0",
      fr: "un-batiment-noir-avec-une-horloge-sur-le-cote-UHHFYUTz_n0",
      it: "un-edificio-nero-con-un-orologio-sul-lato-UHHFYUTz_n0",
      ko: "옆에-시계가-있는-검은색-건물-UHHFYUTz_n0",
      de: "ein-schwarzes-gebaude-mit-einer-uhr-an-der-seite-UHHFYUTz_n0",
      pt: "um-predio-preto-com-um-relogio-ao-lado-UHHFYUTz_n0",
    },
    created_at: "2024-05-15T14:36:12Z",
    updated_at: "2024-05-23T17:52:13Z",
    promoted_at: "2024-05-23T10:59:45Z",
    width: 7050,
    height: 4697,
    color: "#262626",
    blur_hash: "L24_%?I9M{t8I9x^9ERj%hRiITx]",
    description: null,
    alt_description: "a black building with a clock on the side of it",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1715783768839-73794cbce337?ixid=M3w2MTU0MDR8MHwxfGFsbHwyfHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1715783768839-73794cbce337?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHwyfHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1715783768839-73794cbce337?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHwyfHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1715783768839-73794cbce337?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHwyfHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1715783768839-73794cbce337?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHwyfHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1715783768839-73794cbce337",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-black-building-with-a-clock-on-the-side-of-it-UHHFYUTz_n0",
      html: "https://unsplash.com/photos/a-black-building-with-a-clock-on-the-side-of-it-UHHFYUTz_n0",
      download:
        "https://unsplash.com/photos/UHHFYUTz_n0/download?ixid=M3w2MTU0MDR8MHwxfGFsbHwyfHx8fHx8Mnx8MTcxNjQ5MDAyN3w",
      download_location:
        "https://api.unsplash.com/photos/UHHFYUTz_n0/download?ixid=M3w2MTU0MDR8MHwxfGFsbHwyfHx8fHx8Mnx8MTcxNjQ5MDAyN3w",
    },
    likes: 42,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      ugc: {
        status: "rejected",
      },
      health: {
        status: "rejected",
      },
      "business-work": {
        status: "unevaluated",
      },
      wallpapers: {
        status: "rejected",
      },
      "textures-patterns": {
        status: "rejected",
      },
      experimental: {
        status: "rejected",
      },
      film: {
        status: "rejected",
      },
      "architecture-interior": {
        status: "approved",
        approved_on: "2024-05-17T18:44:20Z",
      },
      "3d-renders": {
        status: "rejected",
      },
      "street-photography": {
        status: "rejected",
      },
      travel: {
        status: "rejected",
      },
    },
    asset_type: "photo",
    user: {
      id: "3SCC0WcF-wA",
      updated_at: "2024-05-23T11:47:38Z",
      username: "refargotohp",
      name: "refargotohp",
      first_name: "refargotohp",
      last_name: null,
      twitter_username: null,
      portfolio_url: null,
      bio: "Hello 👋🏼 My name is Pavel, and I am a photographer. I enjoy the photo in any of its manifestations. Sequential shooting, street, studio, portraiture - it's all me. Waiting for you on my social networks - @refargotohp",
      location: null,
      links: {
        self: "https://api.unsplash.com/users/refargotohp",
        html: "https://unsplash.com/@refargotohp",
        photos: "https://api.unsplash.com/users/refargotohp/photos",
        likes: "https://api.unsplash.com/users/refargotohp/likes",
        portfolio: "https://api.unsplash.com/users/refargotohp/portfolio",
        following: "https://api.unsplash.com/users/refargotohp/following",
        followers: "https://api.unsplash.com/users/refargotohp/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1653036388874-dab6bdb375bcimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1653036388874-dab6bdb375bcimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1653036388874-dab6bdb375bcimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "refargotohp",
      total_collections: 1,
      total_likes: 43,
      total_photos: 133,
      total_promoted_photos: 62,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "refargotohp",
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
  },
  {
    id: "Jlll74v6hIk",
    slug: "a-white-sink-sitting-under-a-mirror-in-a-bathroom-Jlll74v6hIk",
    alternative_slugs: {
      en: "a-white-sink-sitting-under-a-mirror-in-a-bathroom-Jlll74v6hIk",
      es: "un-lavabo-blanco-sentado-debajo-de-un-espejo-en-un-bano-Jlll74v6hIk",
      ja: "バスルームの鏡の下に置かれた白い洗面台-Jlll74v6hIk",
      fr: "un-lavabo-blanc-assis-sous-un-miroir-dans-une-salle-de-bain-Jlll74v6hIk",
      it: "un-lavandino-bianco-seduto-sotto-uno-specchio-in-un-bagno-Jlll74v6hIk",
      ko: "욕실-거울-아래에-앉아있는-흰색-세면대-Jlll74v6hIk",
      de: "ein-weisses-waschbecken-unter-einem-spiegel-in-einem-badezimmer-Jlll74v6hIk",
      pt: "uma-pia-branca-sentada-sob-um-espelho-em-um-banheiro-Jlll74v6hIk",
    },
    created_at: "2024-05-15T10:28:49Z",
    updated_at: "2024-05-23T18:04:16Z",
    promoted_at: "2024-05-23T10:59:42Z",
    width: 3608,
    height: 5093,
    color: "#a6a6a6",
    blur_hash: "LB97b8-oM{IV4T%L%MWYt8M{M{j?",
    description: "Dark composition",
    alt_description: "a white sink sitting under a mirror in a bathroom",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1715768731984-681108168122?ixid=M3w2MTU0MDR8MHwxfGFsbHwzfHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1715768731984-681108168122?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHwzfHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1715768731984-681108168122?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHwzfHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1715768731984-681108168122?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHwzfHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1715768731984-681108168122?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHwzfHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1715768731984-681108168122",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-white-sink-sitting-under-a-mirror-in-a-bathroom-Jlll74v6hIk",
      html: "https://unsplash.com/photos/a-white-sink-sitting-under-a-mirror-in-a-bathroom-Jlll74v6hIk",
      download:
        "https://unsplash.com/photos/Jlll74v6hIk/download?ixid=M3w2MTU0MDR8MHwxfGFsbHwzfHx8fHx8Mnx8MTcxNjQ5MDAyN3w",
      download_location:
        "https://api.unsplash.com/photos/Jlll74v6hIk/download?ixid=M3w2MTU0MDR8MHwxfGFsbHwzfHx8fHx8Mnx8MTcxNjQ5MDAyN3w",
    },
    likes: 17,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "r01XoGoEPT8",
      updated_at: "2024-05-23T18:07:49Z",
      username: "rgaleriacom",
      name: "Ricardo Gomez Angel",
      first_name: "Ricardo",
      last_name: "Gomez Angel",
      twitter_username: null,
      portfolio_url: "https://www.rgaleria.com",
      bio: "I'm architect, marketing specialist and photographer. I`m working since years as freelancer photographer for different Swiss companies",
      location: "Switzerland",
      links: {
        self: "https://api.unsplash.com/users/rgaleriacom",
        html: "https://unsplash.com/@rgaleriacom",
        photos: "https://api.unsplash.com/users/rgaleriacom/photos",
        likes: "https://api.unsplash.com/users/rgaleriacom/likes",
        portfolio: "https://api.unsplash.com/users/rgaleriacom/portfolio",
        following: "https://api.unsplash.com/users/rgaleriacom/following",
        followers: "https://api.unsplash.com/users/rgaleriacom/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1492187901140-48ac7eff801c?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1492187901140-48ac7eff801c?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1492187901140-48ac7eff801c?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "ricardogo03",
      total_collections: 0,
      total_likes: 16899,
      total_photos: 1568,
      total_promoted_photos: 452,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "ricardogo03",
        portfolio_url: "https://www.rgaleria.com",
        twitter_username: null,
        paypal_email: null,
      },
    },
  },
  {
    id: "pVSIuA3tJ4M",
    slug: "a-group-of-people-standing-around-a-room-pVSIuA3tJ4M",
    alternative_slugs: {
      en: "a-group-of-people-standing-around-a-room-pVSIuA3tJ4M",
      es: "un-grupo-de-personas-de-pie-alrededor-de-una-habitacion-pVSIuA3tJ4M",
      ja: "部屋の周りに立っている人々のグループ-pVSIuA3tJ4M",
      fr: "un-groupe-de-personnes-debout-autour-dune-piece-pVSIuA3tJ4M",
      it: "un-gruppo-di-persone-in-piedi-intorno-a-una-stanza-pVSIuA3tJ4M",
      ko: "방-주위에-서-있는-한-무리의-사람들-pVSIuA3tJ4M",
      de: "eine-gruppe-von-menschen-die-in-einem-raum-herumstehen-pVSIuA3tJ4M",
      pt: "um-grupo-de-pessoas-em-pe-ao-redor-de-uma-sala-pVSIuA3tJ4M",
    },
    created_at: "2024-01-08T04:38:32Z",
    updated_at: "2024-05-23T18:19:53Z",
    promoted_at: "2024-05-23T10:55:43Z",
    width: 6925,
    height: 4617,
    color: "#402626",
    blur_hash: "L77^Y-%20z9t-pbbn$aKIVRjt6xa",
    description: null,
    alt_description: "a group of people standing around a room",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1704688618021-557e23d44850?ixid=M3w2MTU0MDR8MHwxfGFsbHw0fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1704688618021-557e23d44850?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHw0fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1704688618021-557e23d44850?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHw0fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1704688618021-557e23d44850?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHw0fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1704688618021-557e23d44850?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHw0fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1704688618021-557e23d44850",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-group-of-people-standing-around-a-room-pVSIuA3tJ4M",
      html: "https://unsplash.com/photos/a-group-of-people-standing-around-a-room-pVSIuA3tJ4M",
      download:
        "https://unsplash.com/photos/pVSIuA3tJ4M/download?ixid=M3w2MTU0MDR8MHwxfGFsbHw0fHx8fHx8Mnx8MTcxNjQ5MDAyN3w",
      download_location:
        "https://api.unsplash.com/photos/pVSIuA3tJ4M/download?ixid=M3w2MTU0MDR8MHwxfGFsbHw0fHx8fHx8Mnx8MTcxNjQ5MDAyN3w",
    },
    likes: 16,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "5BbkcIeqO5o",
      updated_at: "2024-05-23T13:04:39Z",
      username: "asafhkalebe",
      name: "Asafh Kalebe",
      first_name: "Asafh",
      last_name: "Kalebe",
      twitter_username: null,
      portfolio_url: null,
      bio: "Keep learning!",
      location: "orlando, FL",
      links: {
        self: "https://api.unsplash.com/users/asafhkalebe",
        html: "https://unsplash.com/@asafhkalebe",
        photos: "https://api.unsplash.com/users/asafhkalebe/photos",
        likes: "https://api.unsplash.com/users/asafhkalebe/likes",
        portfolio: "https://api.unsplash.com/users/asafhkalebe/portfolio",
        following: "https://api.unsplash.com/users/asafhkalebe/following",
        followers: "https://api.unsplash.com/users/asafhkalebe/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1695093090466-5d55b92f6361image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1695093090466-5d55b92f6361image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1695093090466-5d55b92f6361image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "asafhkalebe",
      total_collections: 0,
      total_likes: 46,
      total_photos: 21,
      total_promoted_photos: 1,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "asafhkalebe",
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
  },
  {
    id: "qnQc2iMpacU",
    slug: "gray-train-close-up-photography-qnQc2iMpacU",
    alternative_slugs: {
      en: "gray-train-close-up-photography-qnQc2iMpacU",
      es: "fotografia-de-primer-plano-del-tren-gris-qnQc2iMpacU",
      ja: "灰色の列車のクローズアップ写真-qnQc2iMpacU",
      fr: "photographie-en-gros-plan-de-train-gris-qnQc2iMpacU",
      it: "fotografia-ravvicinata-del-treno-grigio-qnQc2iMpacU",
      ko: "회색-기차-근접-촬영-qnQc2iMpacU",
      de: "grauer-zug-nahaufnahme-qnQc2iMpacU",
      pt: "fotografia-de-close-up-do-trem-cinza-qnQc2iMpacU",
    },
    created_at: "2017-05-30T02:43:47Z",
    updated_at: "2024-05-23T18:25:30Z",
    promoted_at: "2024-05-23T10:55:19Z",
    width: 3648,
    height: 5472,
    color: "#0c2626",
    blur_hash: "LGC?o-s:D*t7M}j?V?az0KRiV?WC",
    description: null,
    alt_description: "gray train close-up photography",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1496112196184-93846ceb7523?ixid=M3w2MTU0MDR8MHwxfGFsbHw1fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1496112196184-93846ceb7523?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHw1fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1496112196184-93846ceb7523?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHw1fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1496112196184-93846ceb7523?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHw1fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1496112196184-93846ceb7523?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHw1fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1496112196184-93846ceb7523",
    },
    links: {
      self: "https://api.unsplash.com/photos/gray-train-close-up-photography-qnQc2iMpacU",
      html: "https://unsplash.com/photos/gray-train-close-up-photography-qnQc2iMpacU",
      download:
        "https://unsplash.com/photos/qnQc2iMpacU/download?ixid=M3w2MTU0MDR8MHwxfGFsbHw1fHx8fHx8Mnx8MTcxNjQ5MDAyN3w",
      download_location:
        "https://api.unsplash.com/photos/qnQc2iMpacU/download?ixid=M3w2MTU0MDR8MHwxfGFsbHw1fHx8fHx8Mnx8MTcxNjQ5MDAyN3w",
    },
    likes: 123,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      "street-photography": {
        status: "approved",
        approved_on: "2024-05-23T05:03:22Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "mA08QQzQf8Y",
      updated_at: "2024-05-23T10:55:19Z",
      username: "charlesdeluvio",
      name: "charlesdeluvio",
      first_name: "charlesdeluvio",
      last_name: null,
      twitter_username: null,
      portfolio_url: null,
      bio: "Graphic designer",
      location: "Montreal",
      links: {
        self: "https://api.unsplash.com/users/charlesdeluvio",
        html: "https://unsplash.com/@charlesdeluvio",
        photos: "https://api.unsplash.com/users/charlesdeluvio/photos",
        likes: "https://api.unsplash.com/users/charlesdeluvio/likes",
        portfolio: "https://api.unsplash.com/users/charlesdeluvio/portfolio",
        following: "https://api.unsplash.com/users/charlesdeluvio/following",
        followers: "https://api.unsplash.com/users/charlesdeluvio/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1515694660956-9133b2f53e3b?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1515694660956-9133b2f53e3b?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1515694660956-9133b2f53e3b?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: null,
      total_collections: 135,
      total_likes: 5244,
      total_photos: 672,
      total_promoted_photos: 292,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: null,
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
  },
  {
    id: "UomtLMysDtk",
    slug: "a-small-vase-with-flowers-on-a-table-UomtLMysDtk",
    alternative_slugs: {
      en: "a-small-vase-with-flowers-on-a-table-UomtLMysDtk",
      es: "un-pequeno-jarron-con-flores-sobre-una-mesa-UomtLMysDtk",
      ja: "テーブルの上に花を生けた小さな花瓶-UomtLMysDtk",
      fr: "un-petit-vase-avec-des-fleurs-sur-une-table-UomtLMysDtk",
      it: "un-piccolo-vaso-con-fiori-su-un-tavolo-UomtLMysDtk",
      ko: "테이블-위에-꽃이-있는-작은-꽃병-UomtLMysDtk",
      de: "eine-kleine-vase-mit-blumen-auf-einem-tisch-UomtLMysDtk",
      pt: "um-pequeno-vaso-com-flores-sobre-uma-mesa-UomtLMysDtk",
    },
    created_at: "2024-05-22T22:42:40Z",
    updated_at: "2024-05-23T18:40:39Z",
    promoted_at: "2024-05-23T10:54:54Z",
    width: 3648,
    height: 5472,
    color: "#8c7340",
    blur_hash: "LsJaTB_Nx]M{-pozWBRQIoV@WBa#",
    description: null,
    alt_description: "a small vase with flowers on a table",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1716346061596-b15ad7ae5391?ixid=M3w2MTU0MDR8MHwxfGFsbHw2fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1716346061596-b15ad7ae5391?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHw2fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1716346061596-b15ad7ae5391?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHw2fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1716346061596-b15ad7ae5391?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHw2fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1716346061596-b15ad7ae5391?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHw2fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1716346061596-b15ad7ae5391",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-small-vase-with-flowers-on-a-table-UomtLMysDtk",
      html: "https://unsplash.com/photos/a-small-vase-with-flowers-on-a-table-UomtLMysDtk",
      download:
        "https://unsplash.com/photos/UomtLMysDtk/download?ixid=M3w2MTU0MDR8MHwxfGFsbHw2fHx8fHx8Mnx8MTcxNjQ5MDAyN3w",
      download_location:
        "https://api.unsplash.com/photos/UomtLMysDtk/download?ixid=M3w2MTU0MDR8MHwxfGFsbHw2fHx8fHx8Mnx8MTcxNjQ5MDAyN3w",
    },
    likes: 14,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "CpBDVgrthTM",
      updated_at: "2024-05-23T17:27:57Z",
      username: "ninjason",
      name: "Jason Leung",
      first_name: "Jason",
      last_name: "Leung",
      twitter_username: null,
      portfolio_url: "https://jasonleung.co",
      bio: "Shooting with Canon R5/R6.\r\nThis is my way of giving back,  keep up with what I photograph on Instagram @xninjason",
      location: "Bay Area, California",
      links: {
        self: "https://api.unsplash.com/users/ninjason",
        html: "https://unsplash.com/@ninjason",
        photos: "https://api.unsplash.com/users/ninjason/photos",
        likes: "https://api.unsplash.com/users/ninjason/likes",
        portfolio: "https://api.unsplash.com/users/ninjason/portfolio",
        following: "https://api.unsplash.com/users/ninjason/following",
        followers: "https://api.unsplash.com/users/ninjason/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1574623311321-015452cd1304image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1574623311321-015452cd1304image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1574623311321-015452cd1304image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "xninjason",
      total_collections: 3,
      total_likes: 0,
      total_photos: 8854,
      total_promoted_photos: 788,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "xninjason",
        portfolio_url: "https://jasonleung.co",
        twitter_username: null,
        paypal_email: null,
      },
    },
  },
  {
    id: "C4EExtDIvwI",
    slug: "a-tree-that-is-standing-in-the-grass-C4EExtDIvwI",
    alternative_slugs: {
      en: "a-tree-that-is-standing-in-the-grass-C4EExtDIvwI",
      es: "un-arbol-que-esta-parado-en-la-hierba-C4EExtDIvwI",
      ja: "草むらに立っている木-C4EExtDIvwI",
      fr: "un-arbre-qui-se-dresse-dans-lherbe-C4EExtDIvwI",
      it: "un-albero-che-sta-in-piedi-nellerba-C4EExtDIvwI",
      ko: "풀밭에-서-있는-나무-C4EExtDIvwI",
      de: "ein-baum-der-im-gras-steht-C4EExtDIvwI",
      pt: "uma-arvore-que-esta-de-pe-na-grama-C4EExtDIvwI",
    },
    created_at: "2024-05-22T18:57:07Z",
    updated_at: "2024-05-23T18:40:46Z",
    promoted_at: "2024-05-23T10:53:03Z",
    width: 4672,
    height: 7008,
    color: "#595959",
    blur_hash: "LVFreGM|IVWX~pRjRjbH4=bGoeoe",
    description: null,
    alt_description: "a tree that is standing in the grass",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1716404084927-176ee37a9dbe?ixid=M3w2MTU0MDR8MHwxfGFsbHw3fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1716404084927-176ee37a9dbe?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHw3fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1716404084927-176ee37a9dbe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHw3fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1716404084927-176ee37a9dbe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHw3fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1716404084927-176ee37a9dbe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHw3fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1716404084927-176ee37a9dbe",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-tree-that-is-standing-in-the-grass-C4EExtDIvwI",
      html: "https://unsplash.com/photos/a-tree-that-is-standing-in-the-grass-C4EExtDIvwI",
      download:
        "https://unsplash.com/photos/C4EExtDIvwI/download?ixid=M3w2MTU0MDR8MHwxfGFsbHw3fHx8fHx8Mnx8MTcxNjQ5MDAyN3w",
      download_location:
        "https://api.unsplash.com/photos/C4EExtDIvwI/download?ixid=M3w2MTU0MDR8MHwxfGFsbHw3fHx8fHx8Mnx8MTcxNjQ5MDAyN3w",
    },
    likes: 42,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "eW3HvoVuQSA",
      updated_at: "2024-05-23T18:12:55Z",
      username: "singleearth",
      name: "Single.Earth",
      first_name: "Single.Earth",
      last_name: null,
      twitter_username: "SingleEarth1",
      portfolio_url: "https://single.earth",
      bio: "World’s first nature-backed currency. \r\n insta@fototamine",
      location: "Tallinn, Estonia",
      links: {
        self: "https://api.unsplash.com/users/singleearth",
        html: "https://unsplash.com/@singleearth",
        photos: "https://api.unsplash.com/users/singleearth/photos",
        likes: "https://api.unsplash.com/users/singleearth/likes",
        portfolio: "https://api.unsplash.com/users/singleearth/portfolio",
        following: "https://api.unsplash.com/users/singleearth/following",
        followers: "https://api.unsplash.com/users/singleearth/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1638886445565-99f07525db79image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1638886445565-99f07525db79image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1638886445565-99f07525db79image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "single_earth",
      total_collections: 0,
      total_likes: 0,
      total_photos: 196,
      total_promoted_photos: 31,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "single_earth",
        portfolio_url: "https://single.earth",
        twitter_username: "SingleEarth1",
        paypal_email: null,
      },
    },
  },
  {
    id: "33FUP-OHSb0",
    slug: "a-close-up-of-a-building-with-a-clock-on-the-side-of-it-33FUP-OHSb0",
    alternative_slugs: {
      en: "a-close-up-of-a-building-with-a-clock-on-the-side-of-it-33FUP-OHSb0",
      es: "un-primer-plano-de-un-edificio-con-un-reloj-a-un-lado-33FUP-OHSb0",
      ja: "側面に時計がある建物のクローズアップ-33FUP-OHSb0",
      fr: "un-gros-plan-dun-batiment-avec-une-horloge-sur-le-cote-33FUP-OHSb0",
      it: "un-primo-piano-di-un-edificio-con-un-orologio-sul-lato-33FUP-OHSb0",
      ko: "측면에-시계가-있는-건물의-클로즈업-33FUP-OHSb0",
      de: "nahaufnahme-eines-gebaudes-mit-einer-uhr-an-der-seite-33FUP-OHSb0",
      pt: "um-close-up-de-um-predio-com-um-relogio-ao-lado-dele-33FUP-OHSb0",
    },
    created_at: "2024-05-22T20:03:17Z",
    updated_at: "2024-05-23T17:53:30Z",
    promoted_at: "2024-05-23T10:52:43Z",
    width: 4000,
    height: 6000,
    color: "#26260c",
    blur_hash: "LDBfk89b0Ma#~T9bWBxt0gWB?FWX",
    description: null,
    alt_description: "a close up of a building with a clock on the side of it",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1716408192311-73e1cf39f4fc?ixid=M3w2MTU0MDR8MHwxfGFsbHw4fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1716408192311-73e1cf39f4fc?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHw4fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1716408192311-73e1cf39f4fc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHw4fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1716408192311-73e1cf39f4fc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHw4fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1716408192311-73e1cf39f4fc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHw4fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1716408192311-73e1cf39f4fc",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-close-up-of-a-building-with-a-clock-on-the-side-of-it-33FUP-OHSb0",
      html: "https://unsplash.com/photos/a-close-up-of-a-building-with-a-clock-on-the-side-of-it-33FUP-OHSb0",
      download:
        "https://unsplash.com/photos/33FUP-OHSb0/download?ixid=M3w2MTU0MDR8MHwxfGFsbHw4fHx8fHx8Mnx8MTcxNjQ5MDAyN3w",
      download_location:
        "https://api.unsplash.com/photos/33FUP-OHSb0/download?ixid=M3w2MTU0MDR8MHwxfGFsbHw4fHx8fHx8Mnx8MTcxNjQ5MDAyN3w",
    },
    likes: 16,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      "textures-patterns": {
        status: "approved",
        approved_on: "2024-05-23T15:42:00Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "FUrPOCwDxzM",
      updated_at: "2024-05-23T15:42:46Z",
      username: "teo",
      name: "Teo Zac",
      first_name: "Teo",
      last_name: "Zac",
      twitter_username: "teofan09",
      portfolio_url: null,
      bio: "Hey you. You're the best!",
      location: "Zürich",
      links: {
        self: "https://api.unsplash.com/users/teo",
        html: "https://unsplash.com/@teo",
        photos: "https://api.unsplash.com/users/teo/photos",
        likes: "https://api.unsplash.com/users/teo/likes",
        portfolio: "https://api.unsplash.com/users/teo/portfolio",
        following: "https://api.unsplash.com/users/teo/following",
        followers: "https://api.unsplash.com/users/teo/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1716452559993-71be744caacaimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1716452559993-71be744caacaimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1716452559993-71be744caacaimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "teo.zac",
      total_collections: 0,
      total_likes: 4283,
      total_photos: 637,
      total_promoted_photos: 34,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "teo.zac",
        portfolio_url: null,
        twitter_username: "teofan09",
        paypal_email: null,
      },
    },
  },
  {
    id: "frbBBb2l2SI",
    slug: "a-close-up-of-a-computer-processor-with-many-components-frbBBb2l2SI",
    alternative_slugs: {
      en: "a-close-up-of-a-computer-processor-with-many-components-frbBBb2l2SI",
      es: "un-primer-plano-de-un-procesador-de-computadora-con-muchos-componentes-frbBBb2l2SI",
      ja: "多くのコンポーネントを持つコンピュータープロセッサのクローズアップ-frbBBb2l2SI",
      fr: "un-gros-plan-dun-processeur-dordinateur-avec-de-nombreux-composants-frbBBb2l2SI",
      it: "un-primo-piano-di-un-processore-di-computer-con-molti-componenti-frbBBb2l2SI",
      ko: "많은-구성-요소가-있는-컴퓨터-프로세서의-클로즈업-frbBBb2l2SI",
      de: "nahaufnahme-eines-computerprozessors-mit-vielen-komponenten-frbBBb2l2SI",
      pt: "um-close-up-de-um-processador-de-computador-com-muitos-componentes-frbBBb2l2SI",
    },
    created_at: "2024-05-23T03:55:58Z",
    updated_at: "2024-05-23T17:54:52Z",
    promoted_at: "2024-05-23T10:52:40Z",
    width: 3840,
    height: 2400,
    color: "#262626",
    blur_hash: "L36*R6^%D#kWT1g2%0xY00xG.9oz",
    description:
      "chip, chipset, AI, artificial intelligence, microchip, technology, innovation, electronics, computer hardware, circuit board, integrated circuit, AI chip, machine learning, neural network, robotics, automation, computing, futuristic, tech, gadget, device, component, semiconductor, electronics component, digital, futuristic tech, AI technology, intelligent system, motherboard, computer, intel, AMD, Ryzen, Core, Apple M1, Apple M2, CPU, processor, computing platform, hardware component, tech innovation, IA, inteligencia artificial, microchip, tecnología, innovación, electrónica",
    alt_description: "a close up of a computer processor with many components",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1716436329478-e4261139e1ca?ixid=M3w2MTU0MDR8MHwxfGFsbHw5fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1716436329478-e4261139e1ca?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHw5fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1716436329478-e4261139e1ca?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHw5fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1716436329478-e4261139e1ca?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHw5fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1716436329478-e4261139e1ca?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHw5fHx8fHx8Mnx8MTcxNjQ5MDAyN3w&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1716436329478-e4261139e1ca",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-close-up-of-a-computer-processor-with-many-components-frbBBb2l2SI",
      html: "https://unsplash.com/photos/a-close-up-of-a-computer-processor-with-many-components-frbBBb2l2SI",
      download:
        "https://unsplash.com/photos/frbBBb2l2SI/download?ixid=M3w2MTU0MDR8MHwxfGFsbHw5fHx8fHx8Mnx8MTcxNjQ5MDAyN3w",
      download_location:
        "https://api.unsplash.com/photos/frbBBb2l2SI/download?ixid=M3w2MTU0MDR8MHwxfGFsbHw5fHx8fHx8Mnx8MTcxNjQ5MDAyN3w",
    },
    likes: 7,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "0UgzHjITxzY",
      updated_at: "2024-05-23T12:27:00Z",
      username: "boliviainteligente",
      name: "BoliviaInteligente",
      first_name: "BoliviaInteligente",
      last_name: null,
      twitter_username: null,
      portfolio_url: null,
      bio: null,
      location: null,
      links: {
        self: "https://api.unsplash.com/users/boliviainteligente",
        html: "https://unsplash.com/@boliviainteligente",
        photos: "https://api.unsplash.com/users/boliviainteligente/photos",
        likes: "https://api.unsplash.com/users/boliviainteligente/likes",
        portfolio:
          "https://api.unsplash.com/users/boliviainteligente/portfolio",
        following:
          "https://api.unsplash.com/users/boliviainteligente/following",
        followers:
          "https://api.unsplash.com/users/boliviainteligente/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1670025355390-63cab1beb2f3image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1670025355390-63cab1beb2f3image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1670025355390-63cab1beb2f3image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: null,
      total_collections: 0,
      total_likes: 0,
      total_photos: 1063,
      total_promoted_photos: 110,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: null,
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
  },
  {
    id: "S5kAQY2F0LE",
    slug: "a-persons-hand-holding-a-large-green-plant-S5kAQY2F0LE",
    alternative_slugs: {
      en: "a-persons-hand-holding-a-large-green-plant-S5kAQY2F0LE",
      es: "la-mano-de-una-persona-sosteniendo-una-gran-planta-verde-S5kAQY2F0LE",
      ja: "大きな緑の植物を持つ人の手-S5kAQY2F0LE",
      fr: "la-main-dune-personne-tenant-une-grande-plante-verte-S5kAQY2F0LE",
      it: "la-mano-di-una-persona-che-tiene-una-grande-pianta-verde-S5kAQY2F0LE",
      ko: "큰-녹색-식물을-들고-있는-사람의-손-S5kAQY2F0LE",
      de: "die-hand-einer-person-die-eine-grosse-grune-pflanze-halt-S5kAQY2F0LE",
      pt: "a-mao-de-uma-pessoa-segurando-uma-grande-planta-verde-S5kAQY2F0LE",
    },
    created_at: "2024-05-14T13:30:01Z",
    updated_at: "2024-05-23T18:36:24Z",
    promoted_at: "2024-05-23T10:48:21Z",
    width: 6762,
    height: 4508,
    color: "#d9d9d9",
    blur_hash: "LHN17T4n~X%NRhfljYoL?ct79YkB",
    description: null,
    alt_description: "a person's hand holding a large green plant",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1715693352133-ffa8caa4e7e8?ixid=M3w2MTU0MDR8MHwxfGFsbHwxMHx8fHx8fDJ8fDE3MTY0OTAwMjd8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1715693352133-ffa8caa4e7e8?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHwxMHx8fHx8fDJ8fDE3MTY0OTAwMjd8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1715693352133-ffa8caa4e7e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHwxMHx8fHx8fDJ8fDE3MTY0OTAwMjd8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1715693352133-ffa8caa4e7e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHwxMHx8fHx8fDJ8fDE3MTY0OTAwMjd8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1715693352133-ffa8caa4e7e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU0MDR8MHwxfGFsbHwxMHx8fHx8fDJ8fDE3MTY0OTAwMjd8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1715693352133-ffa8caa4e7e8",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-persons-hand-holding-a-large-green-plant-S5kAQY2F0LE",
      html: "https://unsplash.com/photos/a-persons-hand-holding-a-large-green-plant-S5kAQY2F0LE",
      download:
        "https://unsplash.com/photos/S5kAQY2F0LE/download?ixid=M3w2MTU0MDR8MHwxfGFsbHwxMHx8fHx8fDJ8fDE3MTY0OTAwMjd8",
      download_location:
        "https://api.unsplash.com/photos/S5kAQY2F0LE/download?ixid=M3w2MTU0MDR8MHwxfGFsbHwxMHx8fHx8fDJ8fDE3MTY0OTAwMjd8",
    },
    likes: 10,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "lz20t7Gfzjs",
      updated_at: "2024-05-23T10:52:37Z",
      username: "chimana",
      name: "Anastasia Judt",
      first_name: "Anastasia",
      last_name: "Judt",
      twitter_username: null,
      portfolio_url: "http://anastasia-judt.com",
      bio: "Hey and welcome!",
      location: "Germany",
      links: {
        self: "https://api.unsplash.com/users/chimana",
        html: "https://unsplash.com/@chimana",
        photos: "https://api.unsplash.com/users/chimana/photos",
        likes: "https://api.unsplash.com/users/chimana/likes",
        portfolio: "https://api.unsplash.com/users/chimana/portfolio",
        following: "https://api.unsplash.com/users/chimana/following",
        followers: "https://api.unsplash.com/users/chimana/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1679412281698-fda10ccb0accimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1679412281698-fda10ccb0accimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1679412281698-fda10ccb0accimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "Chimanaa",
      total_collections: 2,
      total_likes: 0,
      total_photos: 26,
      total_promoted_photos: 2,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "Chimanaa",
        portfolio_url: "http://anastasia-judt.com",
        twitter_username: null,
        paypal_email: null,
      },
    },
  },
];

export const baseUrl = "https://api.unsplash.com/";
